name: Test And Deploy Contract

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - contract/contracts/**

jobs:
  contractTester:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: contract

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install node packages
        run: npm install --production

      # - name: Install ganache-cli
      #   run: npm install -g ganache-cli

      # - name: Launch ganache-cli network
      #   run: ganache-cli &

      - name: Install truffle
        run: npm install -g truffle

      # - name: Test with Truffle test
      #   run: truffle test --network remote

      - name: Deploy Contract to Remote Server
        run: truffle migrate --network remote
        
      - name: Stringify file content
        run: |
          MESSAGE=$(cat CDS_CA.txt)
          echo "MESSAGE=${MESSAGE}" >> $GITHUB_ENV

      - name: Trigger discord webhook with CDS CA
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.CONTRACT_DISCORD_WEBHOOK_URL }}
          content: ${{ env.MESSAGE }}
